import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("exports the GDS2GOO application shell", async () => {
  const html = await readFile(new URL("../out/index.html", import.meta.url), "utf8");
  assert.match(html, /<title>GDS2GOO/);
  assert.match(html, /From GDS layout to the/);
  assert.match(html, /Elegoo Mars 4/);
  assert.match(html, /Generate \.GOO file/);
  assert.match(html, /ZOOM/);
  assert.match(html, /PIXEL GRID/);
  assert.match(html, /SUBSTRATE OUTLINE/);
  assert.match(html, /MEASURE/);
  assert.match(html, /Step-and-repeat/);
  assert.match(html, /Local process recipes/);
  assert.match(html, /Custom circular substrate/);
  assert.match(html, /2-inch wafer · Ø50\.8 mm/);
  assert.match(html, /Microscope slide · 75 × 25 mm/);
  assert.match(html, /A tool by Jorge Parra/);
  assert.match(html, /calibration pattern/);
  assert.match(html, /QUICK GUIDE/);
  assert.match(html, /perform a dry exposure/);
  assert.match(html, /Process metadata/);
  assert.match(html, /Printer orientation check/);
  assert.match(html, /Restore \.run\.json/);
  assert.match(html, /Download experiment bundle/);
  assert.match(html, /Print experimental run sheet/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});
