import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("exports the GDS2GOO application shell", async () => {
  const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
  const source = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
  const photoresists = await readFile(new URL("../lib/photoresists.js", import.meta.url), "utf8");
  assert.match(html, /<title>GDS2GOO/);
  assert.match(html, /favicon\.svg/);
  for (const metadata of ["theme-color", "canonical", "og:site_name", "og:url", "og:image:alt", "twitter:title", "twitter:description", "twitter:image:alt"]) {
    assert.match(html, new RegExp(metadata));
  }
  assert.match(html, /Conversion scope/);
  assert.match(html, /Load a layout/);
  assert.match(html, /NATIVE RASTER/);
  assert.match(html, /Elegoo Mars 4/);
  assert.match(html, /Generate \.GOO file/);
  assert.match(source, /ZOOM/);
  assert.match(source, /PIXEL GRID/);
  assert.match(source, /RESIST RESPONSE/);
  assert.match(source, /405 nm photoresist library/);
  assert.match(photoresists, /MICROPOSIT S1805/);
  assert.match(photoresists, /AR-N 4400-10/);
  assert.match(html, /UV logo GDS example/);
  assert.match(source, /SUBSTRATE OUTLINE/);
  assert.match(source, /MEASURE/);
  assert.match(source, /FULL SCREEN/);
  assert.match(source, /Step-and-repeat/);
  assert.match(source, /Local process recipes/);
  assert.match(source, /Custom circular substrate/);
  assert.match(source, /2-inch wafer · Ø50\.8 mm/);
  assert.match(source, /Microscope slide · 75 × 25 mm/);
  assert.match(html, /A tool by Jorge Parra/);
  assert.match(html, /href="https:\/\/jorpago2\.github\.io\/"/);
  assert.match(html, /https:\/\/doi\.org\/10\.1002\/smtd\.202501336/);
  assert.match(html, /calibration pattern/);
  assert.match(html, /QUICK GUIDE/);
  assert.match(html, /href="#converter"/);
  assert.match(html, /id="converter"/);
  assert.match(html, /perform a dry exposure/);
  assert.match(source, /Process metadata/);
  assert.match(html, /Printer orientation check/);
  assert.match(html, /Restore \.run\.json/);
  assert.match(html, /Download experiment bundle/);
  assert.match(html, /Print experimental run sheet/);
  assert.doesNotMatch(html, /Exposure and orientation/);
  assert.doesNotMatch(html, /PIXEL GRID|SUBSTRATE OUTLINE|LAYOUT SIZE/);
  assert.match(source, /sourceInfo && <>/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});
