import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("exports the GDS2GOO application shell", async () => {
  const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
  const source = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
  const photoresists = await readFile(new URL("../lib/photoresists.js", import.meta.url), "utf8");
  assert.match(html, /<title>GDS2GOO/);
  assert.match(html, /favicon\.svg/);
  for (const metadata of ["theme-color", "canonical", "og:site_name", "og:url", "og:image:alt", "twitter:title", "twitter:description", "twitter:image:alt"]) {
    assert.match(html, new RegExp(metadata));
  }
  assert.match(html, /GDS2GOO/);
  assert.match(html, /Elegoo Mars 4/);
  assert.match(html, /Needs input/);
  for (const section of ["Input", "Mask", "Process", "Export"]) assert.match(html, new RegExp(`>${section}<`));
  assert.match(html, /Start a mask/);
  assert.match(html, /Open GDS/);
  assert.match(html, /Try UV example/);
  assert.match(source, /Generate \.GOO/);
  assert.match(source, /Zoom/);
  assert.match(source, /Pixel grid/);
  assert.match(source, /Resist response/);
  assert.match(source, /405 nm photoresist library/);
  assert.match(photoresists, /MICROPOSIT S1805/);
  assert.match(photoresists, /AR-N 4400-10/);
  assert.match(source, /UV logo GDS example/);
  assert.match(source, /Substrate outline/);
  assert.match(source, /Measure/);
  assert.match(source, /Full screen/);
  assert.match(source, /Step-and-repeat/);
  assert.match(source, /Local process recipes/);
  assert.match(source, /Search by recipe, resist or thickness/);
  assert.doesNotMatch(source, /mobile-panel-preview|Compact live mask preview/);
  assert.match(source, /className="transform-summary"/);
  assert.match(source, /Export generated/);
  assert.match(source, /Custom circular substrate/);
  assert.match(source, /2-inch wafer · Ø50\.8 mm/);
  assert.match(source, /Microscope slide · 75 × 25 mm/);
  assert.doesNotMatch(source, /All tools|href="https:\/\/jorpago2\.github\.io\/"/);
  assert.match(source, /calibration pattern/);
  assert.match(html, /id="workspace"/);
  assert.match(source, /Dry LCD exposure/);
  assert.match(source, /Process metadata/);
  assert.match(source, /Substrate &amp; alignment/);
  assert.match(source, /className="export-dock"/);
  const styles = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
  const tokens = await readFile(new URL("../tokens.css", import.meta.url), "utf8");
  assert.match(styles, /Carbon g10 owns the application UI/);
  assert.match(styles, /@import "\.\.\/tokens\.css"/);
  const carbon = await readFile(new URL("../src/carbon.scss", import.meta.url), "utf8");
  assert.match(carbon, /@use ["']@carbon\/react["']/);
  assert.doesNotMatch(styles, /tailwindcss|@theme inline/);
  assert.match(source, /<ScientificHeader\b/);
  assert.match(source, /product="GDS2GOO"/);
  assert.match(source, /productMark="G"/);
  assert.match(source, /className="workflow-navigation"/);
  assert.match(source, /data-panel-open/);
  assert.doesNotMatch(source, /<(?:button|input|select|textarea|details|summary)\b/);
  for (const component of ["Button", "NumberInput", "TextInput", "Select", "ComboBox", "Checkbox", "Toggle", "Accordion", "FileUploaderDropContainer", "FileUploaderButton", "InlineNotification", "Layer", "Link", "Tag"]) {
    assert.match(source, new RegExp(`<${component}\\b`));
  }
  assert.match(tokens, /--viewer-surface:/);
  assert.doesNotMatch(tokens, /--color-(?:paper|accent|success|warning|error)|--radius-card|--shadow-card/);
  assert.doesNotMatch(styles, /#[0-9a-f]{3,8}|rgba?\(|100vw|overflow-x:\s*hidden/i);
  assert.match(source, /Printer orientation check/);
  assert.match(source, /Restore \.run\.json/);
  assert.match(source, /Experiment bundle/);
  assert.match(source, /Experimental run sheet/);
  assert.doesNotMatch(html, /Exposure and orientation/);
  assert.doesNotMatch(html, /PIXEL GRID|SUBSTRATE OUTLINE/);
  assert.match(source, /sourceInfo && <>/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/i);
});
